return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
        local configs = require("nvim-treesitter.configs")

        configs.setup({
            ensure_installed = {
                "bash",
                "bibtex",
                "c",
                "c_sharp",
                "comment",
                "cpp",
                "css",
                "diff",
                "dockerfile",
                "dot",
                "gdscript",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "go",
                "gomod",
                "graphql",
                "haskell",
                "hcl",
                "html",
                "ini",
                "java",
                "javascript",
                "jsdoc",
                "json",
                "json5",
                "jsonc",
                "julia",
                "kotlin",
                "ledger",
                "lua",
                "make",
                "markdown",
                "markdown_inline",
                "mermaid",
                "ocaml",
                "php",
                "prisma",
                "python",
                "query",
                "r",
                "regex",
                "requirements",
                "rst",
                "ruby",
                "rust",
                "scss",
                "sql",
                "svelte",
                "terraform",
                "toml",
                "tsx",
                "typescript",
                "vimdoc",
                "yaml",
            },
            sync_install = false,
            highlight = { enable = true },
            indent = { enable = true },
        })
    end
}
